using SM.Core;

namespace SM.Editor.SeedData;

internal static partial class NarrativeSeedData
{
    private static partial StoryEventSeed[] CreateStoryEvents()
    {
        return new[]
        {
            Evt(
                "story_event_site_intro_ashen_gate",
                NarrativeMoment.SiteEntered,
                100,
                "dialogue_scene_ashen_gate_intro",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_ashen_gate"), Cond(StoryConditionKind.SiteIs, "site_ashen_gate") },
                new[] { Eff(StoryEffectKind.SetFlag, "story_flag_intro_ashen_gate") }),
            Evt(
                "story_event_boss_bark_ashen_gate",
                NarrativeMoment.BattleStarted,
                200,
                "dialogue_overlay_boss_bark_ashen_gate",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_ashen_gate"), Cond(StoryConditionKind.SiteIs, "site_ashen_gate"), Cond(StoryConditionKind.NodeIs, "4") },
                System.Array.Empty<StoryEffectSeed>()),
            Evt(
                "story_event_boss_defeat_ashen_gate",
                NarrativeMoment.BattleResolved,
                250,
                "dialogue_overlay_boss_defeat_ashen_gate",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_ashen_gate"), Cond(StoryConditionKind.SiteIs, "site_ashen_gate"), Cond(StoryConditionKind.NodeIs, "4") },
                new[] { Eff(StoryEffectKind.SetFlag, "story_flag_gatekeeper_defeated") }),
            Evt(
                "story_event_extract_ashen_gate",
                NarrativeMoment.ExtractCommitted,
                300,
                "story_card_extract_ashen_gate",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_ashen_gate"), Cond(StoryConditionKind.SiteIs, "site_ashen_gate") },
                new[] { Eff(StoryEffectKind.SetFlag, "story_flag_first_clue") }),
            Evt(
                "story_event_site_intro_wolfpine_trail",
                NarrativeMoment.SiteEntered,
                100,
                "dialogue_scene_wolfpine_trail_intro",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_ashen_gate"), Cond(StoryConditionKind.SiteIs, "site_wolfpine_trail") },
                new[] { Eff(StoryEffectKind.SetFlag, "story_flag_intro_wolfpine_trail") }),
            Evt(
                "story_event_boss_bark_wolfpine_trail",
                NarrativeMoment.BattleStarted,
                200,
                "dialogue_overlay_boss_bark_wolfpine_trail",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_ashen_gate"), Cond(StoryConditionKind.SiteIs, "site_wolfpine_trail"), Cond(StoryConditionKind.NodeIs, "4") },
                System.Array.Empty<StoryEffectSeed>()),
            Evt(
                "story_event_boss_defeat_wolfpine_trail",
                NarrativeMoment.BattleResolved,
                250,
                "dialogue_overlay_boss_defeat_wolfpine_trail",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_ashen_gate"), Cond(StoryConditionKind.SiteIs, "site_wolfpine_trail"), Cond(StoryConditionKind.NodeIs, "4") },
                new[] { Eff(StoryEffectKind.SetFlag, "story_flag_grey_fang_defeated") }),
            Evt(
                "story_event_unlock_rift_stalker",
                NarrativeMoment.ExtractCommitted,
                300,
                "toast_unlock_rift_stalker",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_ashen_gate"), Cond(StoryConditionKind.SiteIs, "site_wolfpine_trail") },
                new[] { Eff(StoryEffectKind.UnlockHero, "hero_rift_stalker"), Eff(StoryEffectKind.SetFlag, "story_flag_rift_stalker_joined") }),
            Evt(
                "story_event_site_intro_sunken_bastion",
                NarrativeMoment.SiteEntered,
                100,
                "dialogue_scene_sunken_bastion_intro",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_sunken_bastion"), Cond(StoryConditionKind.SiteIs, "site_sunken_bastion") },
                new[] { Eff(StoryEffectKind.SetFlag, "story_flag_intro_sunken_bastion") }),
            Evt(
                "story_event_boss_bark_sunken_bastion",
                NarrativeMoment.BattleStarted,
                200,
                "dialogue_overlay_boss_bark_sunken_bastion",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_sunken_bastion"), Cond(StoryConditionKind.SiteIs, "site_sunken_bastion"), Cond(StoryConditionKind.NodeIs, "4") },
                System.Array.Empty<StoryEffectSeed>()),
            Evt(
                "story_event_boss_defeat_sunken_bastion",
                NarrativeMoment.BattleResolved,
                250,
                "dialogue_overlay_boss_defeat_sunken_bastion",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_sunken_bastion"), Cond(StoryConditionKind.SiteIs, "site_sunken_bastion"), Cond(StoryConditionKind.NodeIs, "4") },
                new[] { Eff(StoryEffectKind.SetFlag, "story_flag_silent_regent_defeated") }),
            Evt(
                "story_event_unlock_bastion_penitent",
                NarrativeMoment.ExtractCommitted,
                300,
                "toast_unlock_bastion_penitent",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_sunken_bastion"), Cond(StoryConditionKind.SiteIs, "site_sunken_bastion") },
                new[] { Eff(StoryEffectKind.UnlockHero, "hero_bastion_penitent"), Eff(StoryEffectKind.SetFlag, "story_flag_bastion_penitent_joined") }),
            Evt(
                "story_event_site_intro_tithe_road",
                NarrativeMoment.SiteEntered,
                100,
                "dialogue_scene_tithe_road_intro",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_sunken_bastion"), Cond(StoryConditionKind.SiteIs, "site_tithe_road") },
                new[] { Eff(StoryEffectKind.SetFlag, "story_flag_intro_tithe_road") }),
            Evt(
                "story_event_boss_bark_tithe_road",
                NarrativeMoment.BattleStarted,
                200,
                "dialogue_overlay_boss_bark_tithe_road",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_sunken_bastion"), Cond(StoryConditionKind.SiteIs, "site_tithe_road"), Cond(StoryConditionKind.NodeIs, "4") },
                System.Array.Empty<StoryEffectSeed>()),
            Evt(
                "story_event_boss_defeat_tithe_road",
                NarrativeMoment.BattleResolved,
                250,
                "dialogue_overlay_boss_defeat_tithe_road",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_sunken_bastion"), Cond(StoryConditionKind.SiteIs, "site_tithe_road"), Cond(StoryConditionKind.NodeIs, "4") },
                new[] { Eff(StoryEffectKind.SetFlag, "story_flag_inquisitor_defeated") }),
            Evt(
                "story_event_unlock_pale_executor",
                NarrativeMoment.ExtractCommitted,
                300,
                "toast_unlock_pale_executor",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_sunken_bastion"), Cond(StoryConditionKind.SiteIs, "site_tithe_road") },
                new[] { Eff(StoryEffectKind.UnlockHero, "hero_pale_executor"), Eff(StoryEffectKind.SetFlag, "story_flag_pale_executor_joined") }),
            Evt(
                "story_event_aldric_journal_found",
                NarrativeMoment.BattleResolved,
                280,
                "dialogue_scene_aldric_journal",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_sunken_bastion"), Cond(StoryConditionKind.SiteIs, "site_sunken_bastion"), Cond(StoryConditionKind.NodeIs, "3") },
                new[] { Eff(StoryEffectKind.SetFlag, "story_flag_aldric_named") }),
            Evt(
                "story_event_site_intro_ruined_crypts",
                NarrativeMoment.SiteEntered,
                100,
                "dialogue_scene_ruined_crypts_intro",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_ruined_crypts"), Cond(StoryConditionKind.SiteIs, "site_ruined_crypts") },
                new[] { Eff(StoryEffectKind.SetFlag, "story_flag_intro_ruined_crypts") }),
            Evt(
                "story_event_boss_bark_ruined_crypts",
                NarrativeMoment.BattleStarted,
                200,
                "dialogue_overlay_boss_bark_ruined_crypts",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_ruined_crypts"), Cond(StoryConditionKind.SiteIs, "site_ruined_crypts"), Cond(StoryConditionKind.NodeIs, "4") },
                System.Array.Empty<StoryEffectSeed>()),
            Evt(
                "story_event_boss_defeat_ruined_crypts",
                NarrativeMoment.BattleResolved,
                250,
                "dialogue_overlay_boss_defeat_ruined_crypts",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_ruined_crypts"), Cond(StoryConditionKind.SiteIs, "site_ruined_crypts"), Cond(StoryConditionKind.NodeIs, "4") },
                new[] { Eff(StoryEffectKind.SetFlag, "story_flag_silent_archivist_defeated") }),
            Evt(
                "story_event_unlock_aegis_sentinel",
                NarrativeMoment.ExtractCommitted,
                300,
                "toast_unlock_aegis_sentinel",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_ruined_crypts"), Cond(StoryConditionKind.SiteIs, "site_ruined_crypts") },
                new[] { Eff(StoryEffectKind.UnlockHero, "hero_aegis_sentinel"), Eff(StoryEffectKind.SetFlag, "story_flag_aegis_sentinel_joined") }),
            Evt(
                "story_event_site_intro_bone_orchard",
                NarrativeMoment.SiteEntered,
                100,
                "dialogue_scene_bone_orchard_intro",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_ruined_crypts"), Cond(StoryConditionKind.SiteIs, "site_bone_orchard") },
                new[] { Eff(StoryEffectKind.SetFlag, "story_flag_intro_bone_orchard") }),
            Evt(
                "story_event_boss_bark_bone_orchard",
                NarrativeMoment.BattleStarted,
                200,
                "dialogue_overlay_boss_bark_bone_orchard",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_ruined_crypts"), Cond(StoryConditionKind.SiteIs, "site_bone_orchard"), Cond(StoryConditionKind.NodeIs, "4") },
                System.Array.Empty<StoryEffectSeed>()),
            Evt(
                "story_event_relicborn_awakening",
                NarrativeMoment.BattleResolved,
                500,
                "dialogue_scene_relicborn_awakening",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_ruined_crypts"), Cond(StoryConditionKind.SiteIs, "site_bone_orchard"), Cond(StoryConditionKind.NodeIs, "3") },
                new[] { Eff(StoryEffectKind.SetFlag, "story_flag_relicborn_awakened") }),
            Evt(
                "story_event_boss_defeat_bone_orchard",
                NarrativeMoment.BattleResolved,
                250,
                "dialogue_overlay_boss_defeat_bone_orchard",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_ruined_crypts"), Cond(StoryConditionKind.SiteIs, "site_bone_orchard"), Cond(StoryConditionKind.NodeIs, "4") },
                new[] { Eff(StoryEffectKind.SetFlag, "story_flag_root_watcher_defeated") }),
            Evt(
                "story_event_midpoint_reveal",
                NarrativeMoment.ExtractCommitted,
                600,
                "dialogue_scene_midpoint_reveal",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_ruined_crypts"), Cond(StoryConditionKind.SiteIs, "site_bone_orchard") },
                new[] { Eff(StoryEffectKind.SetFlag, "story_flag_midpoint_revealed") }),
            Evt(
                "story_event_unlock_echo_savant",
                NarrativeMoment.ExtractCommitted,
                300,
                "toast_unlock_echo_savant",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_ruined_crypts"), Cond(StoryConditionKind.SiteIs, "site_bone_orchard") },
                new[] { Eff(StoryEffectKind.UnlockHero, "hero_echo_savant"), Eff(StoryEffectKind.SetFlag, "story_flag_echo_savant_joined") }),
            Evt(
                "story_event_aldric_face_revealed",
                NarrativeMoment.BattleResolved,
                520,
                "dialogue_scene_aldric_face",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_ruined_crypts"), Cond(StoryConditionKind.SiteIs, "site_bone_orchard"), Cond(StoryConditionKind.NodeIs, "3"), Cond(StoryConditionKind.FlagSet, "story_flag_relicborn_awakened") },
                new[] { Eff(StoryEffectKind.SetFlag, "story_flag_aldric_face_seen") }),
            Evt(
                "story_event_site_intro_glass_forest",
                NarrativeMoment.SiteEntered,
                100,
                "dialogue_scene_glass_forest_intro",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_glass_forest"), Cond(StoryConditionKind.SiteIs, "site_glass_forest") },
                new[] { Eff(StoryEffectKind.SetFlag, "story_flag_intro_glass_forest") }),
            Evt(
                "story_event_boss_bark_glass_forest",
                NarrativeMoment.BattleStarted,
                200,
                "dialogue_overlay_boss_bark_glass_forest",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_glass_forest"), Cond(StoryConditionKind.SiteIs, "site_glass_forest"), Cond(StoryConditionKind.NodeIs, "4") },
                System.Array.Empty<StoryEffectSeed>()),
            Evt(
                "story_event_boss_defeat_glass_forest",
                NarrativeMoment.BattleResolved,
                250,
                "dialogue_overlay_boss_defeat_glass_forest",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_glass_forest"), Cond(StoryConditionKind.SiteIs, "site_glass_forest"), Cond(StoryConditionKind.NodeIs, "4") },
                new[] { Eff(StoryEffectKind.SetFlag, "story_flag_prism_guardian_defeated") }),
            Evt(
                "story_event_unlock_shardblade",
                NarrativeMoment.ExtractCommitted,
                300,
                "toast_unlock_shardblade",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_glass_forest"), Cond(StoryConditionKind.SiteIs, "site_glass_forest") },
                new[] { Eff(StoryEffectKind.UnlockHero, "hero_shardblade"), Eff(StoryEffectKind.SetFlag, "story_flag_shardblade_joined") }),
            Evt(
                "story_event_site_intro_starved_menagerie",
                NarrativeMoment.SiteEntered,
                100,
                "dialogue_scene_starved_menagerie_intro",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_glass_forest"), Cond(StoryConditionKind.SiteIs, "site_starved_menagerie") },
                new[] { Eff(StoryEffectKind.SetFlag, "story_flag_intro_starved_menagerie") }),
            Evt(
                "story_event_boss_bark_starved_menagerie",
                NarrativeMoment.BattleStarted,
                200,
                "dialogue_overlay_boss_bark_starved_menagerie",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_glass_forest"), Cond(StoryConditionKind.SiteIs, "site_starved_menagerie"), Cond(StoryConditionKind.NodeIs, "4") },
                System.Array.Empty<StoryEffectSeed>()),
            Evt(
                "story_event_boss_defeat_starved_menagerie",
                NarrativeMoment.BattleResolved,
                250,
                "dialogue_overlay_boss_defeat_starved_menagerie",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_glass_forest"), Cond(StoryConditionKind.SiteIs, "site_starved_menagerie"), Cond(StoryConditionKind.NodeIs, "4") },
                new[] { Eff(StoryEffectKind.SetFlag, "story_flag_hunger_warden_defeated") }),
            Evt(
                "story_event_unlock_prism_seeker",
                NarrativeMoment.ExtractCommitted,
                300,
                "toast_unlock_prism_seeker",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_glass_forest"), Cond(StoryConditionKind.SiteIs, "site_starved_menagerie") },
                new[] { Eff(StoryEffectKind.UnlockHero, "hero_prism_seeker"), Eff(StoryEffectKind.SetFlag, "story_flag_prism_seeker_joined") }),
            Evt(
                "story_event_method_debate",
                NarrativeMoment.SiteEntered,
                120,
                "dialogue_scene_method_debate",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_glass_forest"), Cond(StoryConditionKind.SiteIs, "site_glass_forest"), Cond(StoryConditionKind.FlagSet, "story_flag_midpoint_revealed") },
                new[] { Eff(StoryEffectKind.SetFlag, "story_flag_method_debate_started") }),
            Evt(
                "story_event_aldric_whisper",
                NarrativeMoment.BattleResolved,
                400,
                "dialogue_scene_aldric_whisper",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_glass_forest"), Cond(StoryConditionKind.SiteIs, "site_glass_forest"), Cond(StoryConditionKind.NodeIs, "2"), Cond(StoryConditionKind.FlagSet, "story_flag_aldric_face_seen") },
                new[] { Eff(StoryEffectKind.SetFlag, "story_flag_aldric_whisper") }),
            Evt(
                "story_event_clan_split",
                NarrativeMoment.SiteEntered,
                130,
                "dialogue_scene_clan_split",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_glass_forest"), Cond(StoryConditionKind.SiteIs, "site_starved_menagerie") },
                new[] { Eff(StoryEffectKind.SetFlag, "story_flag_clan_split") }),
            Evt(
                "story_event_costs_accepted",
                NarrativeMoment.ExtractCommitted,
                350,
                "dialogue_scene_costs_accepted",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_glass_forest"), Cond(StoryConditionKind.SiteIs, "site_starved_menagerie") },
                new[] { Eff(StoryEffectKind.SetFlag, "story_flag_costs_accepted") }),
            Evt(
                "story_event_site_intro_heartforge_gate",
                NarrativeMoment.SiteEntered,
                100,
                "dialogue_scene_heartforge_gate_intro",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_heartforge_descent"), Cond(StoryConditionKind.SiteIs, "site_heartforge_gate") },
                new[] { Eff(StoryEffectKind.SetFlag, "story_flag_intro_heartforge_gate") }),
            Evt(
                "story_event_boss_bark_heartforge_gate",
                NarrativeMoment.BattleStarted,
                200,
                "dialogue_overlay_boss_bark_heartforge_gate",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_heartforge_descent"), Cond(StoryConditionKind.SiteIs, "site_heartforge_gate"), Cond(StoryConditionKind.NodeIs, "4") },
                System.Array.Empty<StoryEffectSeed>()),
            Evt(
                "story_event_boss_defeat_heartforge_gate",
                NarrativeMoment.BattleResolved,
                250,
                "dialogue_overlay_boss_defeat_heartforge_gate",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_heartforge_descent"), Cond(StoryConditionKind.SiteIs, "site_heartforge_gate"), Cond(StoryConditionKind.NodeIs, "4") },
                new[] { Eff(StoryEffectKind.SetFlag, "story_flag_eternal_bulwark_defeated") }),
            Evt(
                "story_event_unlock_mirror_cantor",
                NarrativeMoment.ExtractCommitted,
                300,
                "toast_unlock_mirror_cantor",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_heartforge_descent"), Cond(StoryConditionKind.SiteIs, "site_heartforge_gate") },
                new[] { Eff(StoryEffectKind.UnlockHero, "hero_mirror_cantor"), Eff(StoryEffectKind.SetFlag, "story_flag_mirror_cantor_joined") }),
            Evt(
                "story_event_site_intro_worldscar_depths",
                NarrativeMoment.SiteEntered,
                100,
                "dialogue_scene_worldscar_depths_intro",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_heartforge_descent"), Cond(StoryConditionKind.SiteIs, "site_worldscar_depths") },
                new[] { Eff(StoryEffectKind.SetFlag, "story_flag_intro_worldscar_depths") }),
            Evt(
                "story_event_boss_bark_worldscar_depths",
                NarrativeMoment.BattleStarted,
                200,
                "dialogue_overlay_boss_bark_worldscar_depths",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_heartforge_descent"), Cond(StoryConditionKind.SiteIs, "site_worldscar_depths"), Cond(StoryConditionKind.NodeIs, "4") },
                System.Array.Empty<StoryEffectSeed>()),
            Evt(
                "story_event_final_boss",
                NarrativeMoment.BattleResolved,
                700,
                "dialogue_scene_final_confrontation",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_heartforge_descent"), Cond(StoryConditionKind.SiteIs, "site_worldscar_depths"), Cond(StoryConditionKind.NodeIs, "4") },
                new[] { Eff(StoryEffectKind.SetFlag, "story_flag_final_boss_defeated") }),
            Evt(
                "story_event_campaign_complete",
                NarrativeMoment.ExtractCommitted,
                900,
                "dialogue_scene_campaign_complete",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_heartforge_descent"), Cond(StoryConditionKind.SiteIs, "site_worldscar_depths") },
                new[] { Eff(StoryEffectKind.SetFlag, "story_flag_campaign_complete"), Eff(StoryEffectKind.SetFlag, "story_flag_endless_open") }),
            Evt(
                "story_event_sacrifice_sequence",
                NarrativeMoment.BattleResolved,
                800,
                "dialogue_scene_sacrifice_sequence",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_heartforge_descent"), Cond(StoryConditionKind.SiteIs, "site_worldscar_depths"), Cond(StoryConditionKind.NodeIs, "4") },
                new[] { Eff(StoryEffectKind.SetFlag, "story_flag_sacrifice_done") }),
            Evt(
                "story_event_echo_farewell",
                NarrativeMoment.ExtractCommitted,
                850,
                "dialogue_scene_echo_farewell",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_heartforge_descent"), Cond(StoryConditionKind.SiteIs, "site_worldscar_depths"), Cond(StoryConditionKind.FlagSet, "story_flag_sacrifice_done") },
                new[] { Eff(StoryEffectKind.SetFlag, "story_flag_echo_farewell") }),
            Evt(
                "story_event_endless_open",
                NarrativeMoment.ExtractCommitted,
                900,
                "toast_endless_open",
                new[] { Cond(StoryConditionKind.ChapterIs, "chapter_heartforge_descent"), Cond(StoryConditionKind.SiteIs, "site_worldscar_depths"), Cond(StoryConditionKind.FlagSet, "story_flag_campaign_complete") },
                new[] { Eff(StoryEffectKind.UnlockMode, "mode_endless_cycle"), Eff(StoryEffectKind.SetFlag, "story_flag_endless_unlocked") }),
            Evt(
                "story_event_town_return_ch1",
                NarrativeMoment.TownEntered,
                150,
                "dialogue_overlay_town_return_ch1",
                new[] { Cond(StoryConditionKind.FlagSet, "story_flag_rift_stalker_joined"), Cond(StoryConditionKind.FlagNotSet, "story_flag_town_return_ch1") },
                new[] { Eff(StoryEffectKind.SetFlag, "story_flag_town_return_ch1") }),
            Evt(
                "story_event_town_return_ch2",
                NarrativeMoment.TownEntered,
                150,
                "dialogue_overlay_town_return_ch2",
                new[] { Cond(StoryConditionKind.FlagSet, "story_flag_pale_executor_joined"), Cond(StoryConditionKind.FlagNotSet, "story_flag_town_return_ch2") },
                new[] { Eff(StoryEffectKind.SetFlag, "story_flag_town_return_ch2") }),
            Evt(
                "story_event_town_return_ch3",
                NarrativeMoment.TownEntered,
                150,
                "dialogue_overlay_town_return_ch3",
                new[] { Cond(StoryConditionKind.FlagSet, "story_flag_echo_savant_joined"), Cond(StoryConditionKind.FlagNotSet, "story_flag_town_return_ch3") },
                new[] { Eff(StoryEffectKind.SetFlag, "story_flag_town_return_ch3") }),
            Evt(
                "story_event_town_return_ch4",
                NarrativeMoment.TownEntered,
                150,
                "dialogue_overlay_town_return_ch4",
                new[] { Cond(StoryConditionKind.FlagSet, "story_flag_prism_seeker_joined"), Cond(StoryConditionKind.FlagNotSet, "story_flag_town_return_ch4") },
                new[] { Eff(StoryEffectKind.SetFlag, "story_flag_town_return_ch4") }),
            Evt(
                "story_event_town_return_ch5",
                NarrativeMoment.TownEntered,
                150,
                "dialogue_overlay_town_return_ch5",
                new[] { Cond(StoryConditionKind.FlagSet, "story_flag_campaign_complete"), Cond(StoryConditionKind.FlagNotSet, "story_flag_town_return_ch5") },
                new[] { Eff(StoryEffectKind.SetFlag, "story_flag_town_return_ch5") }),
        };
    }

    private static partial PresentationTextSeed[] CreatePresentationTexts()
    {
        return new[]
        {
            Presentation("story_card_extract_ashen_gate", "첫 단서 회수", "Ashen Gate의 잔해에서 첫 번째 Heartforge 파편을 확보했다."),
            Presentation("toast_endless_open", "새 모드 개방", "Endless Cycle이 해금되었다."),
            Presentation("toast_unlock_aegis_sentinel", "영웅 합류", "Aegis Sentinel가 원정대에 합류했다."),
            Presentation("toast_unlock_bastion_penitent", "영웅 합류", "참회 방벽수가 원정대에 합류했다."),
            Presentation("toast_unlock_echo_savant", "영웅 합류", "Echo Savant가 원정대에 합류했다."),
            Presentation("toast_unlock_mirror_cantor", "영웅 합류", "거울 성가대가 원정대에 합류했다."),
            Presentation("toast_unlock_pale_executor", "영웅 합류", "창백한 집행자가 원정대에 합류했다."),
            Presentation("toast_unlock_prism_seeker", "영웅 합류", "Prism Seeker가 원정대에 합류했다."),
            Presentation("toast_unlock_rift_stalker", "영웅 합류", "균열 추적자가 원정대에 합류했다."),
            Presentation("toast_unlock_shardblade", "영웅 합류", "Shardblade가 원정대에 합류했다."),
        };
    }
}

