using SM.Core;

namespace SM.Editor.SeedData;

internal static partial class NarrativeSeedData
{
    private static partial HeroLoreSeed[] CreateHeroLore()
    {
        return new[]
        {
            Lore("hero_lore_iron_warden", "hero_iron_warden", NarrativeTier.Support, 3, "", "Iron Warden", "왕국 정규군의 마지막 구세대 방패병. 동료들은 Gate 붕괴 때 전사했고, 본인만 살아남았다. 충성의 대상이었던 왕도, 지켜야 할 전선도 사라진 지금, 남은 것은 몸에 새겨진 습관뿐이다. 누군가를 지키는 것 외에는 자신의 존재 이유를 설명할 방법이 없기에, 원정대의 전열에 선다. 신념이 아니라 관성에 가까운 의무감이지만, 그 관성이 전선을 지탱하는 가장 단단한 축이 된다.", new[] { "질서의 얼굴, 초반 안전판" }),
            Lore("hero_lore_crypt_guardian", "hero_crypt_guardian", NarrativeTier.Support, 3, "", "Crypt Guardian", "언데드 묘역의 여성 수호자. 석관 속에 잠든 것은 뼈가 아니라 사랑했던 이들의 기억이며, 그 기억이 소실되면 진정한 죽음이 찾아온다. 묘역을 지키는 행위는 곧 죽은 문명의 마지막 증인으로 서는 것이다. 원정에 합류한 것은 외부 세력이 묘역을 훼손하는 것을 막기 위해서였으나, 여정이 깊어지면서 그녀가 지키는 기억 속에 모든 세력의 죄가 기록되어 있음을 증언해야 하는 역할을 떠안게 된다.", new[] { "죽은 문명의 죄를 증언" }),
            Lore("hero_lore_fang_bulwark", "hero_fang_bulwark", NarrativeTier.Background, 1, "", "Fang Bulwark", "야수족 현장성의 상징", new[] { "야수족 현장성의 상징" }),
            Lore("hero_lore_oath_slayer", "hero_oath_slayer", NarrativeTier.Support, 3, "", "Oath Slayer", "왕국의 맹세검(Oath Blade). 집정관 회의의 명령을 물리적으로 집행하는 도구로 훈련받은 여성 처형자이며, 스스로도 그렇게 정체성을 정의해 왔다. 그녀의 존재는 칼 그 자체로 규정되었고, 칼이 향하는 곳에 의문을 품는 것은 맹세의 위반이라 배웠다. 그러나 원정 중 정화 재판의 실상과 격자 오용의 진실을 목격하면서, 자신이 휘둘러 온 칼이 정의가 아니라 은폐를 위한 것이었을 가능성에 직면한다. 무기로서의 정체성 밖에서 자신이 누구인지를 처음으로 묻기 시작하며, 칼을 드는 손이 처음으로 망설인다.", new[] { "왕국의 폭력성과 명분을 드러내는 칼" }),
            Lore("hero_lore_pack_raider", "hero_pack_raider", NarrativeTier.Lead, 6, "hook_pack_treaty", "Pack Raider", "이리솔 부족 본대의 젊은 무리 지도자. 냄새와 발자국, 매듭으로 세상을 읽는다. 변방문이 무너진 뒤 형제 회조가 200일 넘게 돌아오지 않자, 솔라룸 사제 단린과 '동맹이 아니라 동행'으로 변방문 안쪽을 함께 본다. 강옹의 흰 끈 화살을 받아들인 것이지, 솔라룸을 받아들인 것이 아니다.", new[] { "이리솔은 시조의 죄를 두고 갈라져 있다 — 잊고 살아남자는 분리파(회조), 외부와 영원히 적대하자는 강경파, 직면하자는 본대(이빨바람). 형제 회조가 분리파 노선으로 그의 길을 막으면서, 분노가 아니라 노선으로 갈라선 형제를 안고 가야 한다.", "ch5에서 이빨바람은 회조를 억지로 회담에 끌어오지 않는다. 돌소리 신호로 '오지 않지만 끊지도 않은' 형제를 확인하고, 피의 서약 매듭을 아직 짓지 않은 채 자리를 비워 둔다. 무리의 반쪽을 잃고도 냄새를 지우지 않는 쪽을 택한다." }),
            Lore("hero_lore_grave_reaver", "hero_grave_reaver", NarrativeTier.Background, 1, "", "Grave Reaver", "파괴된 충성의 잔재", new[] { "파괴된 충성의 잔재" }),
            Lore("hero_lore_longshot_hunter", "hero_longshot_hunter", NarrativeTier.Support, 3, "", "Longshot Hunter", "원정대의 실무 보급 담당이자 장거리 정찰병. 정치적 명분이나 신앙적 사명에는 관심이 없고, 원정대가 내일도 먹고 살아남을 수 있는가에만 집중한다. 세력 간 갈등을 냉정한 실무자의 눈으로 관찰하며, 대의보다 보급선이 끊기는 것을 더 두려워한다. 정치를 꿰뚫어 보는 눈이 있지만, 그 통찰을 굳이 공유하려 들지는 않는다. 살아 돌아가는 것이 유일한 목표이며, 그 목표가 원정대 전체의 생존과 겹치는 한에서만 협력한다.", new[] { "원정 실무자의 시선" }),
            Lore("hero_lore_trail_scout", "hero_trail_scout", NarrativeTier.Support, 3, "", "Trail Scout", "야수족과 인간 영역의 경계에서 자란 혼혈 여성 정찰병. 어느 쪽에도 완전히 속하지 못한 경험이 오히려 양쪽 사이의 완충재 역할을 가능하게 만들었다. 긴장이 극에 달할 때 건조한 농담으로 분위기를 꺾는 능력이 있으며, 본인은 이것을 생존 기술이라 부른다. 유머 아래에는 어디에도 속하지 못한 자의 외로움이 있지만, 그녀가 그것을 드러내는 일은 거의 없다. 두 세계 사이의 다리가 되는 것이 소명이라기보다는, 그 위치 말고는 설 곳이 없기 때문이다.", new[] { "유머와 경계의 완충재" }),
            Lore("hero_lore_dread_marksman", "hero_dread_marksman", NarrativeTier.Background, 1, "", "Dread Marksman", "언데드 원거리 처형자. 감정을 소실한 채 깨어났으며, 기억은 남아 있으나 그 기억에 붙어 있어야 할 감정이 없다. 표적을 지정하면 실행하고, 실행이 끝나면 다음 표적을 기다린다. 이 냉혹한 효율성이 원정대에서는 전술적 자산이지만, 동료들에게는 불안의 원천이기도 하다. 본인에게 '왜 싸우느냐'는 질문은 의미가 없다. 싸우는 것만 남았기에 싸울 뿐이다.", new[] { "언데드의 냉혹한 효율" }),
            Lore("hero_lore_dawn_priest", "hero_dawn_priest", NarrativeTier.Lead, 6, "hook_faith_crack", "Dawn Priest", "솔라룸의 젊은 여사제. 본 대성당에서 정화 의례와 성물 기록을 맡다가 변방 원정에 자원한 첫 사제 계급 출신이다. 집정관 합의제 안에서 '보러 가는 자리'를 자청했고 본인은 신앙의 확장이라 믿었으나, 실제로는 단현 학파의 변방 도굴을 지켜볼 관찰자에 가깝다. 빛과 자수, 새겨진 이름, 흙 위의 흔적을 먼저 읽는 사람이다.", new[] { "변방에서 단린은 자신이 외운 단현 학설이 방패가 아니라 칼이 될 수 있음을 본다. 정화 재판의 '정결/오염' 분류가 사람을 번호로 접는 언어였음을 인정하면서, 동기는 '신앙의 수호'에서 '한 사람으로 증언하기'로 옮겨간다.", "그녀가 평생 외운 문장을 설계한 단현은 이미 죽었고, 그 학설을 정치 자원으로 바꾸려는 백규가 학자장이다. ch5에서 단린은 단현 일지의 마지막 부탁을 백규 앞에서 인용하고, 사제 인장을 내려놓은 채 한 사람으로 증언한다. 본 대성당으로 돌아가지 않고 새 신앙을 찾는다." }),
            Lore("hero_lore_grave_hexer", "hero_grave_hexer", NarrativeTier.Lead, 6, "hook_memory_debt", "Grave Hexer", "회상 결사의 기억 증언자. 첫 도시 학살의 전수 기억을 의식으로 물려받아 자기 책임으로만 붙들어 온, 결사에서 가장 오래된 축의 인물이다. 직접 목격자는 아니지만 그 기억의 무게를 누구보다 잘 안다. 무거운 진실을 농담과 사소한 기억으로 씹어 넘기는 시간 거리감이 캠페인 중반의 구명줄이다.", new[] { "회상 결사는 학살 기억을 어떻게 다룰지에서 갈라진다 — 보존하며 화해의 여지를 남기려는 묵향과, 단죄 명단으로 책임을 묻는 흑지. 그 명단 위에는 묵향 자신의 이름도 올라 있다.", "ch5에서 묵향은 흑지의 명단을 들고 도시 안으로 들어가고, 전수 기억의 일부를 단린에게 맡긴다. 자기 이름을 명단에서 빼 달라 청하지 않고, '자리가 비면 잎 하나는 끼워 두라'며 자신이 보았다는 표시만 남긴다. 흑지와의 명단 문제는 미해결로 남는다." }),
            Lore("hero_lore_storm_shaman", "hero_storm_shaman", NarrativeTier.Support, 3, "", "Storm Shaman", "야수족 씨족의 여성 의례 관장자이자 공동체 치유사. 순환의 숨결(Breath of the Cycle) 의례를 통해 씨족의 기억과 유대를 유지하는 역할을 맡고 있다. 원정에 합류한 것은 무리에서 떨어져 나온 전사들의 영혼을 돌보기 위해서다. 그녀는 Heartforge의 공명을 본능적으로 감지하며, 이것이 씨족 의례의 뿌리와 연결되어 있다는 직감을 품고 있다. 전투보다 치유를, 파괴보다 복원을 우선하며, 씨족의 의례가 끊어지지 않는 한 희망은 남아 있다고 믿는다.", new[] { "야수족 공동체의 의례" }),
            Lore("hero_lore_rift_stalker", "hero_rift_stalker", NarrativeTier.Background, 1, "", "Rift Stalker", "한때 원정대의 움직임을 추적하던 야수족 추적자. 균열의 잔향을 읽는 감각 때문에 적진에서는 길잡이였고, 합류 뒤에는 약한 측면을 먼저 찾아내는 정찰 자산이 된다.", new[] { "적에서 동맹으로 돌아선 첫 균열 추적자" }),
            Lore("hero_lore_bastion_penitent", "hero_bastion_penitent", NarrativeTier.Background, 1, "", "Bastion Penitent", "왕국 방벽 교리의 실패를 몸으로 겪은 참회자. 그는 무너진 전선을 변명하지 않고, 같은 붕괴가 원정대 안에서 반복되지 않도록 가장 위험한 자리에 선다.", new[] { "왕국 내부 균열을 증언하는 방벽수" }),
            Lore("hero_lore_pale_executor", "hero_pale_executor", NarrativeTier.Background, 1, "", "Pale Executor", "감정보다 표식을 먼저 읽는 언데드 집행자. 처형은 신념이 아니라 남은 질서를 끝내는 절차이며, 원정대는 그 냉정함을 마지막 일격이 필요한 순간에만 끌어낸다.", new[] { "표식을 끝까지 따라가는 창백한 집행자" }),
            Lore("hero_lore_aegis_sentinel", "hero_aegis_sentinel", NarrativeTier.Support, 3, "", "Aegis Sentinel", "원정대가 처음으로 조우한 각성 Relicborn. 격자 노드 하나가 완전히 파괴되면서 강제 각성했으며, 격자 복원이라는 대의보다는 눈앞의 노드를 지키겠다는 본능에 가깝게 움직인다. 언어 소통이 극히 제한적이고, 의사 표현은 거의 행동으로만 이루어진다. 원정대를 보호하는 이유를 말로 설명한 적은 없지만, 위기 상황에서 반복적으로 전열에 서는 행위 자체가 신뢰의 증명이 된다. 말이 아니라 몸으로 증명하는 존재이며, Relicborn이 적이 아님을 처음으로 보여주는 사례다.", new[] { "Relicborn의 문지기" }),
            Lore("hero_lore_echo_savant", "hero_echo_savant", NarrativeTier.Lead, 6, "hook_memory_custody", "Echo Savant", "그물 결사의 시조 본인. 첫 도시 학살 직후 침묵 의무를 받아 도시 입구를 1800년 동안 의례적으로 다시 묶어 온 '문을 닫은 손'이다. 평소에는 평범한 인간으로 살며 외부 세계는 결사의 존재조차 몰랐다. 오래 닫아 둔 손이라 열 때도 먼저 떨린다고 말한다 — 책임의 감각이 설정 설명보다 먼저 오는 인물이다.", new[] { "1800년 침묵을 끝내려는 외부 활동가 노선(공한)과, 시조의 약속을 글자 그대로 수호하려는 침묵 강경파(침월)가 충돌한다. 침묵이 학파의 야심을 막지 못했음을 알기에 그는 침묵을 끝내는 쪽을 택한다.", "ch5에서 공한은 도시 안으로 들어가는 대가로 침월에게 결사 후예의 자리를 박탈당한다. 다시 봉인되지 않고, 결사 안의 이름을 잃은 채 문밖의 외부 증언자로 남는다. '잊어라. 나는 기억하겠다.' 빈 손으로, 안에서 나오려는 사람과 밖에서 들어오려는 사람을 모두 붙잡겠다고 말한다." }),
            Lore("hero_lore_shardblade", "hero_shardblade", NarrativeTier.Background, 1, "", "Shardblade", "중후반 전열 돌파 장치", new[] { "중후반 전열 돌파 장치" }),
            Lore("hero_lore_prism_seeker", "hero_prism_seeker", NarrativeTier.Background, 1, "", "Prism Seeker", "진실 추적자", new[] { "진실 추적자" }),
            Lore("hero_lore_mirror_cantor", "hero_mirror_cantor", NarrativeTier.Support, 3, "", "Mirror Cantor", "거울 의례로 흐트러진 명령과 기억을 맞추는 성가대. 전장의 제어를 걷어내는 동시에, 각 세력이 서로를 어떻게 비추는지 끝까지 확인하게 만드는 인물이다.", new[] { "정화와 기억을 한 박자로 묶는 성가대" }),
        };
    }
}
