using System.Collections.Generic;

using SM.Core.Contracts;

namespace SM.Combat.Model;

public sealed record BattleUnitReadModel(
    string Id,
    string Name,
    TeamSide Side,
    DeploymentAnchorId Anchor,
    string RaceId,
    string ClassId,
    CombatVector2 Position,
    float CurrentHealth,
    float MaxHealth,
    bool IsAlive,
    CombatActionState ActionState,
    BattleActionType? PendingActionType,
    string? TargetId,
    string? TargetName,
    float WindupProgress,
    float CooldownRemaining,
    float CurrentEnergy,
    float MaxEnergy,
    bool IsDefending,
    float Barrier = 0f,
    IReadOnlyList<string>? StatusIds = null,
    float HeadAnchorHeight = 2f,
    float NavigationRadius = 0.5f,
    float SeparationRadius = 0.7f,
    float PreferredRangeMin = 0f,
    float PreferredRangeMax = 0f,
    float EngagementSlotRadius = 1.2f,
    int EngagementSlotCount = 4,
    CombatEntityKind EntityKind = CombatEntityKind.RosterUnit,
    string CurrentSelector = "",
    string CurrentFallback = "",
    float RetargetLockRemaining = 0f,
    float FrontlineGuardRadius = 2.5f,
    float ClusterRadius = 2.5f,
    string ArchetypeId = "",
    string CharacterId = "",
    string RoleInstructionId = "",
    string RoleTag = "",
    string SignatureActiveId = "",
    string SignatureActiveName = "",
    string FlexActiveId = "",
    string FlexActiveName = "",
    PositioningIntentKind PositioningIntent = PositioningIntentKind.None,
    ReevaluationReason PositioningReplanReason = ReevaluationReason.None,
    int PositioningIntentRevision = 0,
    float AttackSpeed = 0f,
    float BasicAttackCooldown = 0f,
    float SkillHaste = 0f,
    string SignaturePassiveId = "",
    string SignaturePassiveName = "",
    string FlexPassiveId = "",
    string FlexPassiveName = "",
    IReadOnlyList<string>? TacticRuleSummaries = null,
    DominantHand DominantHand = DominantHand.Right);

public sealed record BattleSimulationStep(
    int StepIndex,
    float TimeSeconds,
    IReadOnlyList<BattleUnitReadModel> Units,
    IReadOnlyList<BattleEvent> Events,
    bool IsFinished,
    TeamSide? Winner);
