<#
.SYNOPSIS
4096-entry Q16.16 sin turn-LUT 생성기 (ADR-0029 §LUT/angle). editor/tool 전용 — player build 미실행.

.DESCRIPTION
SM.Core.Numerics.SinLut(raw int 상수 테이블)을 생성한다. 런타임은 이 상수만 읽어 MathF 없이 sin/cos를
계산하므로 cross-platform bit-exact가 성립한다. 생성 환경(이 스크립트의 [Math]::Sin)은 산출물이 상수라
런타임 결정성에 영향을 주지 않는다.

값 규칙: Values[i] = round(sin(2π·i/N) × 65536, half-away-from-zero), i ∈ [0, N). N은 2의 거듭제곱.
재생성 시 TrigLutTests의 핀 해시(TableHashV1)도 출력값으로 갱신할 것 — 그래야 락 테스트가 의미를 가진다.

.EXAMPLE
pwsh -File tools/gen-sin-lut.ps1
pwsh -File tools/gen-sin-lut.ps1 -EntryCount 4096
#>
param(
    [int]$EntryCount = 4096,
    [string]$OutFile = "Assets/_Game/Scripts/Runtime/Core/Numerics/SinLut.cs"
)
$ErrorActionPreference = 'Stop'

$N = $EntryCount
$indexBits = [int][Math]::Round([Math]::Log($N, 2))
if ([Math]::Pow(2, $indexBits) -ne $N) { throw "EntryCount는 2의 거듭제곱이어야 함: $N" }
$indexShift = 32 - $indexBits
$fracMask = (1L -shl $indexShift) - 1
$fracMaskLiteral = '0x{0:X}u' -f $fracMask

# 값 계산
$values = New-Object 'int[]' $N
$twoPi = [Math]::PI * 2.0
for ($i = 0; $i -lt $N; $i++) {
    $s = [Math]::Sin($twoPi * $i / $N) * 65536.0
    $values[$i] = [int][Math]::Round($s, [System.MidpointRounding]::AwayFromZero)
}

# FNV-1a 64 over little-endian 4-byte ints (BattleStateCanonicalHash와 동일 규약, endianness 비의존)
$offset = [System.Numerics.BigInteger]::Parse("14695981039346656037")
$prime  = [System.Numerics.BigInteger]::Parse("1099511628211")
$mask   = [System.Numerics.BigInteger]::Parse("18446744073709551615") # 2^64-1
$hash = $offset
foreach ($v in $values) {
    $u = ([int64]$v) -band 0xFFFFFFFFL   # two's complement 저(低)32bit
    foreach ($shift in 0, 8, 16, 24) {
        $b = [int](($u -shr $shift) -band 0xFF)
        $hash = ($hash -bxor $b) -band $mask
        $hash = ($hash * $prime) -band $mask
    }
}
$hex = $hash.ToString('x').PadLeft(16, '0')
$hex = $hex.Substring($hex.Length - 16)

# 배열 본문 (16/line, 12-space indent)
$sb = [System.Text.StringBuilder]::new()
for ($i = 0; $i -lt $N; $i++) {
    if ($i % 16 -eq 0) { [void]$sb.Append("`n            ") }
    [void]$sb.Append($values[$i])
    if ($i -lt $N - 1) { [void]$sb.Append(', ') }
}
$body = $sb.ToString()

$content = @"
// <auto-generated> tools/gen-sin-lut.ps1 로 생성 — 손으로 편집하지 말 것.
// 재생성: pwsh -File tools/gen-sin-lut.ps1  (이후 TrigLutTests의 핀 해시 TableHashV1 갱신)
// $N-entry Q16.16 sin turn-LUT (ADR-0029 §LUT/angle). raw int 상수만 — 런타임 MathF 미사용으로 cross-platform bit-exact.
namespace SM.Core.Numerics
{
    /// <summary>
    /// 결정적 sin turn-LUT 데이터. <see cref="FixedMath.SinTurns"/>/<see cref="FixedMath.CosTurns"/>가 읽는다.
    /// full turn = 2^32(<see cref="AngleTurn32"/> BAM)의 상위 $indexBits bit가 인덱스, 하위 $indexShift bit가 보간 fraction.
    /// 값 = round(sin(2π·i/$N)·65536, half-away-from-zero), 값역 [-65536, 65536] = Fixed32 raw.
    /// </summary>
    public static class SinLut
    {
        public const int EntryCount = $N;
        public const int IndexBits = $indexBits;
        /// <summary>BAM(2^32)에서 인덱스를 뽑는 우시프트 = 32 - IndexBits.</summary>
        public const int IndexShift = $indexShift;
        /// <summary>보간 fraction 마스크 = (1 &lt;&lt; IndexShift) - 1.</summary>
        public const uint InterpFractionMask = $fracMaskLiteral;

        public static readonly int[] Values =
        {$body
        };
    }
}
"@

$abs = Join-Path (Get-Location) $OutFile
[System.IO.File]::WriteAllText($abs, $content, [System.Text.UTF8Encoding]::new($false))

Write-Host "SinLut.cs 생성: $OutFile"
Write-Host "EntryCount=$N IndexBits=$indexBits IndexShift=$indexShift InterpFractionMask=$fracMaskLiteral"
Write-Host "TableHashV1 = $hex"
Write-Host ("cardinal 샘플: [0]={0} [{1}]={2} [{3}]={4} [{5}]={6}" -f `
    $values[0], ($N / 4), $values[$N / 4], ($N / 2), $values[$N / 2], (3 * $N / 4), $values[3 * $N / 4])
