using System.Collections.Generic;
using SM.Combat.Model;

namespace SM.Unity.UI.Town;

public sealed record TownRecruitCardViewState(
    string Title,
    string Body,
    string ActionLabel,
    bool IsEnabled);

public sealed record TownDeployButtonViewState(
    DeploymentAnchorId Anchor,
    string Label);

public sealed record TownScreenViewState(
    string Title,
    string LocaleStatus,
    string LocaleKoLabel,
    string LocaleEnLabel,
    string CampaignSummaryText,
    string PreviousChapterLabel,
    bool CanSelectPreviousChapter,
    string NextChapterLabel,
    bool CanSelectNextChapter,
    string PreviousSiteLabel,
    bool CanSelectPreviousSite,
    string NextSiteLabel,
    bool CanSelectNextSite,
    string CurrencySummary,
    string RosterText,
    string BlueprintSummaryText,
    string RecruitSummaryText,
    IReadOnlyList<TownRecruitCardViewState> RecruitCards,
    string SelectedHeroSummaryText,
    string DeployPreviewText,
    IReadOnlyList<TownDeployButtonViewState> DeployButtons,
    string TeamPostureButtonLabel,
    string CycleHeroLabel,
    bool CanCycleHero,
    string CycleItemLabel,
    bool CanCycleItem,
    string ScoutLabel,
    bool CanScout,
    string RetrainActiveLabel,
    bool CanRetrainActive,
    string RetrainPassiveLabel,
    bool CanRetrainPassive,
    string FullRetrainLabel,
    bool CanFullRetrain,
    string DismissLabel,
    bool CanDismiss,
    string RefitLabel,
    bool CanRefit,
    string CycleBoardLabel,
    bool CanCycleBoard,
    string CycleNodeLabel,
    bool CanCycleNode,
    string ToggleNodeLabel,
    bool CanToggleNode,
    string CyclePermanentLabel,
    bool CanCyclePermanent,
    string EquipPermanentLabel,
    bool CanEquipPermanent,
    string StatusText,
    string RerollLabel,
    string SaveLabel,
    string LoadLabel,
    string ReturnToStartLabel,
    bool CanReturnToStart,
    string ExpeditionActionLabel,
    string QuickBattleLabel,
    bool CanQuickBattle);
